### ISSUE TITLE
検証（単体試験）の追加

### ISSUE THREAD

**Issue by LWisteria** [openmps/openmps#14]
妥当性確認(validation)は[#11](https://bitbucket.org/OpenMps/openmps/issues/11) [#13](https://bitbucket.org/OpenMps/openmps/issues/13) [#14](https://bitbucket.org/OpenMps/openmps/issues/14)等で実施しているが、検証(verification)はやっていない。

余裕があれば単体試験として追加すべき

https://bitbucket.org/OpenMps/openmps/issues/16

**Comment by maru10t** [comment]
### 今後のPR計画
* Computerコンストラクタのテスト
* searchNeighborのテスト, (探索された粒子IDを正解と比較)
* searchDensityテスト

**Comment by maru10t** [comment]
[bitbucket issue](https://bitbucket.org/OpenMps/openmps/issues/16/-----------)

**Comment by maru10t** [comment]
### コンストラクタ系メモ

* 全フィールド(コンストラクタ, moveで値が設定されるもの)
     * particles,environment,grid,neighbor,ppe,du,ecs,originalX,positionWall,positionWallPre
* publicにアクセスできるフィールド
     * particles,environment

今後の粒子密度計算をテストにつなげるために、grid,neighborもテストが必要なはず.
とりあえずは particles,environmentのみだけ含めて, 一旦PR発行した。

異なるパラメータでのテスト + moveのテスト を行うために、テストフィクスチャクラスに一つのComputerインスタンス保持ではなく、各テストケースごとにComputerインスタンス作成にすることが必要
(ココらへんのコードは作成したので 指摘次第で#16 or 次のPRに含める)

**Comment by maru10t** [comment]
次は ここまでのテストコードの Visual Studio 対応が課題。
まず Visual Studio へ Google Test  を導入する。

**Comment by maru10t** [comment]
標準的にサポートされているので特にインストールは必要なし。
https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-google-test-for-cpp?view=vs-2019

**Comment by maru10t** [comment]
<最下部に移動>

**Comment by LWisteria** [comment]
そういえば、 https://github.com/openmps/openmps/tree/master/src/OpenMps/test あたりに、テストの使い方（コンパイル方法と実行方法）のREADMEを書いたほうが良いですね

**Comment by maru10t** [comment]
後回しにしてきたwindows用の環境構築した
* [git-scm](https://git-scm.com/): ターミナルからのgit操作ができるクライアントをインストールした。
* [Boost 1.70 Getting Started](https://www.boost.org/doc/libs/1_70_0/more/getting_started/windows.html): boostをダウンロードして配置、VSからインクルードした。(Build From the Visual Studio IDE の項目参考)
* OpenMpsのプロジェクトを汚さずにboostを追加したい
     * VC++ディレクトリ`$(VC_IncludePath);$(WindowsSDK_IncludePath);`に配置? 

テスト用プロジェクトを新たに作成してパスの設定中。

**Comment by maru10t** [comment]
@LWisteria 
boostは VC_IncludePath or WindowsSDK_IncludePath に配置するのが良いですか？ 
もしくは、OpenMPSのプロジェクトファイルを変更せずに、VC++のインクルードパスに追加することは可能ですか？

**Comment by maru10t** [comment]
本体 + テストコード動作まで到達した。ディレクトリとパス設定等を見直してプルリクにする。

#### やったことメモ

* `bootstrap.bat` と `.\b2 -j 4 install` で boost 1.70 をコンパイルした
* とりあえずプロジェクトごとにVC++設定で、追加のインクルードディレクトリ、ライブラリディレクトリにboostを指定
* Debug/OpenMps.exe は5分ほど待機したが計算進まず。Release/OpenMps.exeは以下の通り動いた。(Debugは、Debugコンソールで出力済みとか、入力待ちとかそういうやつだろう。)
```
C:\Users\takafumi.maruishi\Workspace\openmps\src\x64\Release>.\OpenMps.exe ../../../Benchmark/DamBreak/Sample.xml
サブディレクトリまたはファイル result は既に存在します。
8016 particles
#00000: t=  0.0000 (00000),         8016 particles, @ 08/06 11:24:10 (    0.06)
#00001: t=  0.0050 (00010),         8016 particles, @ 08/06 11:24:11 (    1.52)
#00002: t=  0.0103 (00021),         8016 particles, @ 08/06 11:24:13 (    3.31)
#00003: t=  0.0152 (00037),         8016 particles, @ 08/06 11:24:15 (    5.66)
#00004: t=  0.0200 (00060),         8016 particles, @ 08/06 11:24:19 (    9.13)
```

**Comment by LWisteria** [comment]
@maru10t boostは各環境でインストール先が違うはずなので、自分のユーザーで既定で読み込める場所に置いて設定しておいてください。方法は問いません。プロジェクトは変更しないようにお願いします。

**Comment by LWisteria** [comment]
なお私の場合は、Microsoft.Cpp.x64.userに設定しています。

**Comment by maru10t** [comment]
memo: Computer_Constructor.cpp で テストケース名にDensityTestが残っている

**Comment by maru10t** [comment]
@LWisteria こちらレビューお願いします。
#22(googletestのVSプロジェクト), #23(クラス名リネーム)

**Comment by maru10t** [comment]
now: レビュー待ちの間に、searchNeighbor/Densityのテストを組んでいる

**Comment by LWisteria** [comment]
@maru10t 今度からでいいですが、PRだしたら、そっちにレビュー依頼と、assignee設定およびレビュアーの要求を出しておいてもらえますか（後から見落としがちになるので・・・）

**Comment by maru10t** [comment]
@LWisteria すみません、PR運用について了解しました。

**Comment by LWisteria** [comment]
いつも作業忘れるのでメモ：Linuxでのgoogletestのビルド時に`cmake -DCMAKE_CXX_COMPILER=clang++ ..`にしないとgccでビルドされてclangを使っているOpenMps本体とリンクがコケる（どこかに書いたほうが良いかもしれない）

**Comment by maru10t** [comment]
memo: cmakeでのvs用プロジェクトファイル生成, Makefileの分離を行った。動作チェック > makefile をlinuxで行うのがまだ。次回作業する。

**Comment by LWisteria** [comment]
> いつも作業忘れるのでメモ：Linuxでのgoogletestのビルド時に`cmake -DCMAKE_CXX_COMPILER=clang++ ..`にしないとgccでビルドされてclangを使っているOpenMps本体とリンクがコケる（どこかに書いたほうが良いかもしれない）

これは、testディレクトリにREADMEを作って、実行方法手順とかと一緒に書くのがいいかも

**Comment by maru10t** [comment]
~~ついでにtest側のmakefileをgcc使用に書き替えるところをやります~~ merged

**Comment by maru10t** [comment]
次は近傍粒子探査`SearchNeighbor()`のテストコードを作成します。

**Comment by maru10t** [comment]
### めも: FowardTimeの流れ

高精度化 or 安定化 を施してない場合の一番簡単なケースでは
1. environemnt.Dt(), environment.SetNextT(): 時間刻み設定 & 時間を進める
1. SearchNeighbor(): 近傍粒子探索してグリッドへ格納
1. SearchNeighborDensity(): 粒子数密度を計算
1. ComputeExplicitForces(): 陽的な計算(重力+粘性の寄与により粒子位置を修正)
1. ComputeNeighborDensities():  粒子数密度を再計算
1. ComputeImplicitForces(): 陰的な計算(圧力勾配の寄与により粒子位置を修正)

* 高精度ラプラシアン(MPS_HL)は推奨のようなのでテストにも含めよう
      * Khayyer and Gotoh (2010) , 後藤本 p85

**Comment by maru10t** [comment]
ComputeExplicitForces, ComputeImplicitForces に対応して
* 微分演算子: Gradient, Laplacian
* 逆行列: ConjugateGradient

次はこの2つの演算をテストを書いたら良さそう。

**Comment by LWisteria** [comment]
SearchNeighbor()で試験してしまいましたけど、よく考えたらGrid.hpp単体に対する試験をやってもよかったかもしれませんね

**Comment by maru10t** [comment]
なるほど。次はどの部分のテストを書いていくべきでしょうか？
@LWisteria

**Comment by LWisteria** [comment]
着実に（後で困りにくい）のはGrid.hppも単体試験しておくことですが、まぁSearchNeighbor()が動いていることを考えると（＆Grid.hppはあんまり計算の本質ではないので）、後回しにしてExplicitForceあたりでも良いかもしれません

**Comment by maru10t** [comment]
わかりました。(ちょっと気分を変えたいので) 木曜からExplicitForceの方に着手してみます。

**Comment by maru10t** [comment]
現在めも: 
* 書いているコード: 粘性応力を生む速度場を設定 u = ( ax^2 + by^2, ... ) して ComputeImplicitForces による 1ステップでの速度変化をテスト
     * ラプラシアンのテストを列挙. (二階微分の値自体の比較、微分演算子としての性質)
* 高精度ラプラシアン(MPS_HL)で計算すると解析値と2倍程度(?)ずれるが、標準MPSラプラシアンでは解析値と一致する?。(検証中)
* とりあえず標準MPSラプラシアンでテストを書いてしまって、あとでMPS_HLの不一致を考えるつもり。午後までに書けるかな(目標)。

**Comment by maru10t** [comment]
* ラプラシアンの精度, N vs Error の図をついでにプロットしておきたい, (暇があったら)
      * 影響半径 r_e は l0 の2倍程度にfixするが、与えられた空間サイズL に対して, l0を小さくして粒子数を多くすることで精度をコントロールする

**Comment by maru10t** [comment]
(コメントをPRへ移行)

**Comment by maru10t** [comment]
休憩。再開したらMPS_HSのラプラシアンの係数修正を少し試す。その後PRにまとめる。

**Comment by maru10t** [comment]
### ComputeImplicitForces() のテスト内容構想

考え中。
関数に含まれる処理は4つ. ポアソン方程式を解き、圧力を決定、粒子位置・速度に修正を加える。
1. SetPressurePoissonEquation() 係数行列を設定
     * 粒子の隣接をもとにして非ゼロ要素の場所をチェック?
     * 係数行列の成分をバルク部分で比較?
1. SolvePressurePoissonEquation() 共役勾配法で解く
     * テスト側で用意した対称行列を解かせてチェック？
1. 圧力を代入
1. ModifiyByPressureGradient() 圧力に応じて粒子位置・速度修正
     *

**Comment by maru10t** [comment]
#### SetPressurePoissonEquation() めも

係数行列の決定法。ダミー粒子は影響ないよう0,1などとする
* 非対角項 `A(i,j) = (2*DIM/lambda/n0)*w(xi-xj)`
* 対角項 `A(i,i) = - sum_j A(i,j) (j != i)`

右辺ベクトル
* `b(i) = -rho/n0/dt/ * spped`
* `speed`は粒子数の瞬間増加速度(Dn/Dt)を表す。`NeighborDensityVariationSpeed(i)`として計算

解ベクトル
* 初期値として直前の圧力を代入

**Comment by maru10t** [comment]
### 私的チェック事項, WIP外す前に

* 条件分岐まとめられない？
* 関数, 変数のスコープは制限できる？
* 変数はconstexpr / const にできる? 参照にできる？
* インデントは統一されているか？
* ハードコードは避けられない？
* 依存関係, とくにヘッダ > Makefile
* プロジェクトファイル vcxproj, sln の更新を確認
* auto,using,decltypeへ置き換えられない？
* std:: 付けるの忘れてない？

**Comment by maru10t** [comment]
~~TODO: Makefileにも新たなテストファイル群を追加~~

**Comment by LWisteria** [comment]
*.cppが全部ビルド対象なので追加不要では？

**Comment by maru10t** [comment]
たしかに...

**Comment by maru10t** [comment]
@LWisteria 
次はどちらを作業するべきでしょうか 
* 高精度ラプラシアン(MPS_HL)の係数合わないバグを解消 (定数倍合わないことはわかっている。その原因を考える)
* ComputerImplicitForces のテストを作成 （主にPoisson方程式のテスト)

**Comment by LWisteria** [comment]
とりあえずHLが合わない問題は、バグチケットを切って別作業にしましょうか。

で、どちらから作業しても良いとは思いますが、前者は他の人（私とか）でも別作業できることを考えると、 @maru10t には後者を引き続きやってもらうほうが良いかなぁとは思います。

とは言うものの、両方とも同じぐらいの優先度だと思うので、気分で決めてもらって良いです。

**Comment by maru10t** [comment]
@LWisteria 
教科書の式と比較してもすぐには分からなかったので(今の僕では変数を一個一個見ていって考えなきゃいけないかなあ)、先にPoisson方程式の方を作業します。

**Comment by maru10t** [comment]
@LWisteria 
> バグチケットを切って別作業

これはバグ的なラベルを付けたissueを立てればよいでしょうか？

**Comment by LWisteria** [comment]
@maru10t 

> これはバグ的なラベルを付けたissueを立てればよいでしょうか？

はい、それでお願いします。

※バグチケットなので、再現手順も忘れずに書いておいてください

**Comment by maru10t** [comment]
ざっと手元でテストを書き終わった。
PRが大きくなりすぎそうなので、以下の2つに分ける。

### ImplicitForces の PR計画

PRその1 **MERGED** #32
* SetPressurePoissonEquation(), 係数行列 A = (a_ij) の性質
     * 次元n = 粒子数
     * i と j が隣接 => a_ij != 0
     * 対称行列 a_ij = a_ji
     * 対角・非対角の等式 a_ii = -Σa_ij (i!=j)

PRその2 <- なう #33 
* SolvePressurePoissonEquation() 共役勾配法のテスト
    * 解析解との比較
         * 自明行列 A = k E (k定数, E単位行列) の解
         * 少し非自明な行列 A (4x4行列, 掃出し法で求解できる見やすい行列) の解

PRその3
* ModifyByPressureGradient() 圧力勾配力による位置・速度の修正
     * Gradient演算子の値
     * 速度, 位置更新されているか

**Comment by LWisteria** [comment]
3つでもいい気はしますね。

**Comment by maru10t** [comment]
> 
> 
> 3つでもいい気はしますね。

そうですね, 3つにします。

**Comment by LWisteria** [comment]
3つに分けたことで、test_ComputerImplicitForcesのファイル名が名前と中身が一致しなくなってますね・・・。

あと、よく考えたら、行列の性質は検査してますが、値そのものの検査はできていない気がします。理論的に自明なものを用意できる気がするので、検査を追加したほうが良いかと思います。

**Comment by LWisteria** [comment]
というか、このissueでずっとやってると長いし分かりづらくなりそうですね・・・。ファイル単位ぐらいでissue切ったほうが良かったかもしれません（今からでもやります？

**Comment by maru10t** [comment]
> ファイル単位のissue分け
やります！ 目下の「Computer.hppの単体試験追加」に分けましょうか

**Comment by LWisteria** [comment]
あ、ファイル単位というのは、test_XXXX.cppという意味でした。

**Comment by maru10t** [comment]
あっ、なるほど

**Comment by LWisteria** [comment]
それぐらいの単位にしておくと、残りの作業量なども見えますし。

まぁなのでとりあえず、ざっとでいいので、今終わっているのも含めて、いくつぐらいのファイルでどういう試験をするかという計画を書いてもらっていいですか？（今の #38 が一段落してからでよいので）

それを見て良さそうであれば、それぞれでissue作りましょうか。

**Comment by maru10t** [comment]
分かりました。賛成します。
はい、#38作業後に、計画をここに書きますね。

**Comment by maru10t** [comment]
@LWisteria 文字コードはVisual Studio側で設定していますか？

**Comment by LWisteria** [comment]
@maru10t VisualStudio側でソースを追加するとBOMありUTF8に自動でなると思いますが、そうなってないでしょうか？不安ならファイル複製で新しいファイルを作ると良いかと思います。

**Comment by maru10t** [comment]
自動でなるんですね。試して確認してみます。

**Comment by maru10t** [comment]
### テストの計画

~~**書きかけ, 次回作業初めに書いてしまう**~~ まず ForwardTime() まで.

// 今終わっているのも含めて計画

* ForwardTime()
	* SearchNeighbor(), ComputeNeighborDensities() 
		* test_ComputerNumberDensity.cpp [merged]
			* 粒子数密度計算ComputerNumberDensity()の動作を、距離関数の値と性質、保持している近傍粒子ID、粒子数密度の値 を見てチェック
		* test_ComputerConstructor.cpp [merged]
			* Computerのコンストラクタの動作を、フィールドの定数値、粒子数・位置を見てチェック

	* ComputeExplicitForces()
		* test_ComputerExplicitForces.cpp [merged]
			* 粒子を速度分布を持たせて正方格子状に配置し、ExplicitForces()前後で中心粒子の位置・速度変化を解析解と比較してチェック
			* 速度分布は、2次関数/三角関数 を与える
	
	* ComputeImplicitForces()
		* test_ComputerImplicitForces.cpp  [merged]
			* 圧力ポアソン方程式を離散化SetPressurePoissonEquation()を 行列A, ベクトルb の性質・値を見てチェック
			* TODO: 行列A, ベクトルbの値自体の比較, ファイル名変更 (NeighborDensityVariationSpeedのテスト実装後に作業)
		* test_ComputerConjugateGradient.cpp [PR発行中] [#45]
			* 共役勾配法SolvePressurePoissonEquation()を, Aに対称行列を与えて解析解と比較してチェック
			* 対称行列は、単位行列/4x4行列/1次元Poisson方程式の離散化行列 を与える
		* test_NeighborDensityVariationSpeed.cpp [#44]
			* 粒子数密度増加速度の計算NeighborDensityVariationSpeed() を、粒子分布を与えて解析解と比較してチェック
			* 標準MPS, 高精度MPS_SPP の2通り分書く
		* test_ModifiedByPressureGradient.cpp
			* 圧力勾配による位置・速度更新ModifyByPressureGradient()を、テスト用の圧力分布を与えて 位置・速度変化を解析解と比較してチェック
			* 圧力分布は、2次関数/三角関数 を与える

	(以下2つはいりますか？)
	* #MPS_ECS, ComputeErrorCorrection() 誤差修正量の計算
		* test_ComputeErrorCorrection.cpp
			* (何をここでテストすべきか？  Dn/Dt, n-n0/n0の値はtest_NeighborDensityVariationSpeed.cppでチェックする)
	* #MPS_DS, SaveX(), DynamicStabilize() DS法 人口斥力追加 [#46]
        	* test_DynamicStabilize.cpp
			* 粒子間距離を変えて, αだけめり込むと非ゼロになることをチェック
			* 粒子間の幾何学的ベクトルの計算、平行・垂直な位置ベクトル(r//, r⊥)の値をチェック

**Comment by maru10t** [comment]
> test_ModifiedByPressureGradient.cpp

を作業中

**Comment by maru10t** [comment]
P(x,z) = 10*z として粒子を配置 (5x5格子, 中心粒子における値を評価)
```
dpx: 2.22045e-16, dpz: 11.2132
```
少しずれる。調整中。

**Comment by LWisteria** [comment]
@maru10t すみません、計画のところ見落としてました。とりあえずその計画で良いと思うので、まだ未作成のところのissueを発行してもらえますか？

> #MPS_DS, SaveX(), DynamicStabilize() DS法 人口斥力追加

はほしいところです。

**Comment by maru10t** [comment]
@LWisteria issue作成, 人工斥力テストの実装了解です。

**Comment by maru10t** [comment]
目下の目標は本体へのCI追加 #42 ですが、ViennaCL原因のCI失敗問題 #50 があり、本体でも同様の問題が起こるはずなので、#50 解決に取り組めば良いでしょうか？ @LWisteria

**Comment by LWisteria** [comment]
@maru10t #50 はまぁ雑用みたいなものなので、残る関数の試験の作成を優先して良いと思います。

**Comment by maru10t** [comment]
@LWisteria わかりました。#44 粒子数密度増加のテストに取り組みます。

**Comment by LWisteria** [comment]
個別のチケットに振り分けられているのでこいつは閉じておきますね。
