### ISSUE TITLE
CIを追加する

### ISSUE THREAD

**Issue by LWisteria** [openmps/openmps#29]
#14 が整備されつつあるので、CIを導入したい

**Comment by LWisteria** [comment]
結果をSlackに通知する機能はまだbotに搭載されていないっぽいので、[CI側で手動で設定しなければならない](https://github.com/marketplace/actions/slack-notify)っぽい。

**Comment by LWisteria** [comment]
#31 でやり方は分かったので、あとは

* 実際に単体試験を実行する
* Visual Studio(msbuild)でもやる

ぐらいが必要ですね。

**Comment by LWisteria** [comment]
@maru10t 単体試験のどこかキリがついたあたりで、残りの作業をお願いできますか（練習も兼ねて）

**Comment by maru10t** [comment]
@LWisteria 単体試験の実行, msbuildへの対応, 了解しました。ImplicitForceテストのマージ後に作業します。

**Comment by maru10t** [comment]
次回作業はまず、こちらに手を付けます。

**Comment by LWisteria** [comment]
@maru10t これ終わってると思うので閉じておきます
