### ISSUE TITLE
本体(Main.cpp)のCI

### ISSUE THREAD

**Issue by LWisteria** [openmps/openmps#42]
#29 で単体試験のCIは入ったが、本体のサンプル(main)でビルド確認とエラーなく実行が完了すること、ぐらいは試験しておいたほうが良さそう

**Comment by LWisteria** [comment]
> エラーなく実行が完了する

今のSample.xmlだと少し系が大きすぎる/CIするには時間が長すぎるかもなので要検討

**Comment by LWisteria** [comment]
@maru10t #29 の続きということで（ちょっと雑用気味になってしまいますが）、これもお願いできますか？

**Comment by maru10t** [comment]
Linuxの方でいうと、OpenMps/test/Makefileのmakeとtest_OpenMps実行が試験されていて、今度はOpenMps/MakefileのmakeとOpenMps本体実行の試験を追加する、ということですね。
了解です。@LWisteria
