### ISSUE TITLE
CIのmsbuildでViennaCL原因でコンパイル失敗

### ISSUE THREAD

**Issue by maru10t** [openmps/openmps#50]
#48 作業中に発生。
* GithubAction上で、msbuildでのViennaCLのコンパイルが失敗
* ViennaCL -> Boost に切り替えるとコンパイルは成功する。
      * こちらはConjugateGradientにおいて実行時例外で落ちる

**Comment by LWisteria** [comment]
#40 で色々試してもらった結果を改めて見てもやっぱり原因がわからないですね・・・。難しい。

**Comment by maru10t** [comment]
#51 で解消したので閉じます。
* 原因: Computer(std::move(Computer()))していた（Computerを作ってmoveしてmoveコンストラクタでコピー
