### ISSUE TITLE
SPPなしだと粒子数密度増加速度の単体試験に落ちる

### ISSUE THREAD

**Issue by LWisteria** [openmps/openmps#55]
https://github.com/openmps/openmps/pull/41#issuecomment-603080599 で発見された問題

試験が悪いのか本体側が悪いのか調査して、修正する必要がある

**Comment by LWisteria** [comment]
#53 に関係はある・・・？かは不明

**Comment by LWisteria** [comment]
これを進めて何が嬉しいかと言うと、実は #12 の問題は別にあったという可能性があって、それが判明するからです

**Comment by aokomoriuta** [comment]
試験が悪いので #12 は関係ないです
